### ISSUE TITLE
关于hand-write-api

### ISSUE THREAD

**Issue by ryuuc** [dusionlike/vue-dusion-keyboard#1]
非常棒的项目，h5用我要适配下，请问手写识别的api你们接的哪家的，后端看起来像.net core

**Comment by dusionlike** [comment]
手写识别是同事在网上找的DLL，因为不知道有没有版权所以不敢放上来。api自己写的，用的.NET WebApi，需要的话留个邮件给你发一份源码

**Comment by dusionlike** [comment]
> 非常棒的项目，h5用我要适配下，请问手写识别的api你们接的哪家的，后端看起来像.net core

手写识别是同事在网上找的DLL，因为不知道有没有版权所以不敢放上来。api自己写的，用的.NET WebApi，需要的话留个邮件给你发一份源码

**Comment by ryuuc** [comment]
非常感谢，ry2u@outlook.com

**Comment by cangshudada** [comment]
> > 非常棒的项目，h5用我要适配下，请问手写识别的api你们接的哪家的，后端看起来像.net core
> 
> 手写识别是同事在网上找的DLL，因为不知道有没有版权所以不敢放上来。api自己写的，用的.NET WebApi，需要的话留个邮件给你发一份源码

能不能也发我一份大佬，非常感谢，15342240569@163.com

**Comment by shanewoo** [comment]
能不能也发我一份大佬，非常感谢，shane@ciwce.com
