### ISSUE TITLE
离线手写

### ISSUE THREAD

**Issue by nangongxiaomo** [dusionlike/vue-dusion-keyboard#3]
离线手写 可否给个demo

**Comment by dusionlike** [comment]
给个邮箱------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;nangongxiaomo&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月18日(星期四) 下午5:17
收件人:&nbsp;&quot;dusionlike/vue-dusion-keyboard&quot;<vue-dusion-keyboard@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[dusionlike/vue-dusion-keyboard] 离线手写 (#3)

**Comment by nangongxiaomo** [comment]
1457960500@qq.com
